spring:
  config:
    import:
      - application-google.yml
      - application-kakao.yml
      - application-naver.yml
      - application-dev-rds.yml
      - application-dev-jwt.yml
#      - 'aws-parameterstore:'

  # jpa
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    show-sql: true


  # 404 페이지 처리, 404
  web:
    resources:
      add-mappings: false


  #spring security filter log
  logging:
    level:
      org:
        springframework:
          security: DEBUG



# redis, my properties
redis:
  network:
    host: localhost
    port: 6379

images:
  upload-path: "/home/ubuntu/images/guesthouse/"
  member-profile : "images/memberprofile/"
  room-dir: "images/room/"

logging:
  org:
    hibernate:
      SQL: debug
      type:
        descriptor:
          sql: trace

log:
  config:
    level: TRACE
    path: "/home/ubuntu/log"
    log-filename: "main-project-log"
    err-log-filename: "main-project-log-err"

#aws:
#  paramstore:
#    enabled: true
#    prefix: /config
#    profile-separator: _
#    name: main-project-server

